### ISSUE TITLE
[공통] 엔트리 하드웨어 연결 오류

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone2#1]
엔트리 하드웨어 연결 프로그램 상위 버전(1.7.x 이상)에서 페트론 V2 연결 시도 시 연결이 안되고 계속 연결 중인 상태로 나옵니다.
※ 드론파이터도 동일합니다.

![image](https://user-images.githubusercontent.com/42791314/62336961-93c6ea80-b50d-11e9-925e-f467aec4540b.png)

**Comment by realwolf** [comment]
하드웨어 연결 오류 수정하였습니다.

엔트리가 예전에는 모든 시리얼 통신 장치에 연결하여 데이터 송수신을 확인하는 방식을 사용하였다면
지금은 하드웨어의 이름을 보고 연결하는 방식을 사용하는 것으로 보입니다.

하드웨어 장치 연결은 드론파이터와 페트론 V2 모두  Windows 10, Windows 7에서 연결이 되는 것을 확인하였습니다.

**Comment by HhanGgun** [comment]
정상적으로 연결되는 것 확인하였습니다. 감사합니다.
