### ISSUE TITLE
[페트론V2] LED 동작 오류

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone2#2]
엔트리 오프라인 프로그램(버전 2.0.5)에서 하드웨어 연결이 되는 경우가 있는데, 다음과 같이 동작 오류가 발생합니다.
- 드론 LED가 선택한 색상과 다른 색상으로 켜짐(ex: 눈 초록 → 노랑, 눈 파랑 → 보라)

![엔트리 블록](https://user-images.githubusercontent.com/42791314/62339796-41d79200-b518-11e9-90eb-6a690ab73573.png)

**Comment by realwolf** [comment]
실행 중단 시 장치를 초기화 할 때 LED를 수동 설정으로 모두 0으로 초기화 한 후 수동 설정으로 기본색을 빨간색으로 설정하여 생긴 문제입니다. 이미 빨간색이 설정된 상태에서 추가로 파란색이나 녹색을 설정하는 것으로 판단하기 때문에 파란색으로 설정할 경우 자주색, 녹색으로 설정할 경우 노란색으로 표시되는 것입니다.

이 오류는 장치 초기화 및 해당 블럭 자체를 LedModeColor를 사용하는 것으로 변경하였습니다.
현재는 LED를 끄는 블럭과 플래그를 사용하는 블럭 두 종류만 수동 설정으로 동작합니다.

**Comment by HhanGgun** [comment]
LED 정상 동작 확인하였습니다. 감사합니다.
