### ISSUE TITLE
[공통] 엔트리 블록 사용 관련 오류

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone2#3]
엔트리 블록을 '블록 집합소'에서 '블록 조립소'로 이동시키거나(drag&drop) 조립할 때 잘 되지 않는 현상이 발생한다고 합니다.(지사의 선생님들 의견)

**Comment by realwolf** [comment]
엔트리 최신 버젼이 좀 더 무거워졌는지 전보다 느린 반응을 보여주기는 합니다.
이 부분은 저희가 해결하기는 어려울 것 같습니다.

**Comment by HhanGgun** [comment]
네 알겠습니다. 감사합니다.
