### ISSUE TITLE
[페트론V2] 페트론 V2 드론 연결 시 Vehicle mode가 드라이브로 설정

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone2#4]
페트론 V2 드론을 연결하였는데 Vehicle mode가 드라이브로 설정됩니다. 엔트리 연결 전에 조종기 설정에서 Vehicle mode를 드론으로 변경하거나 엔트리에서 블록을 사용하여 변경해도 다시 드라이브 상태로 돌아갑니다.

**Comment by realwolf** [comment]
장치에서 State 데이터를 받았을 때 현재 동작 모드와 관련없는 상태인 경우 강제로 모드를 변경하게하는 코드가 있는데 자동차의 것을 그대로 비행기에 사용하여 발생한 문제였습니다. 현재는 수정하였습니다.

**Comment by HhanGgun** [comment]
수정해주신 것 확인하였습니다. 감사합니다.
