### ISSUE TITLE
[페트론V2] 드론 LED 블록 중 RGB 조합 예시 블록 오류 발생

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone2#5]
드론 LED 블록 중 RGB 조합 예시 블록을 사용하면 오류가 발생합니다.

![image](https://user-images.githubusercontent.com/42791314/62911422-483ef700-bdbf-11e9-8cfd-f97dfc73f9d6.png)

**Comment by realwolf** [comment]
블록에 Interval 입력칸을 추가하면서 생긴 변수에 대한 정의가 빠진 블럭이 있었습니다.
관련된 블럭들을 확인하여 수정하였습니다.

**Comment by HhanGgun** [comment]
해당 블록 정상 동작 확인하였습니다. 감사합니다.
