### ISSUE TITLE
[페트론V2] 드론 LED 블록 중 RGB 선택 블록과 RGB 조합 블록의 사용 방식 통일 요청

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone2#6]
드론 LED 블록 중 RGB 선택 블록과 RGB 조합 블록의 사용 방식이 달라서 동작하는데 차이가 발생합니다. 사용 방식을 RGB 조합 블록의 방식과 동일하게 변경 요청드립니다.

![image](https://user-images.githubusercontent.com/42791314/62911589-dca95980-bdbf-11e9-916a-bacce472f370.png)
![image](https://user-images.githubusercontent.com/42791314/62911608-efbc2980-bdbf-11e9-9233-3bb74672a283.png)

**Comment by realwolf** [comment]
LED 초기화 방법을 수정하면서 상단 블럭 또한 LedModeColor를 사용하는 것으로 변경하였습니다.

**Comment by HhanGgun** [comment]
변경해주신 것 확인하였습니다. 감사합니다.
