### ISSUE TITLE
[엔트리] 드론 연결 시 센서 관련 블록 중에 자동차(드라이브)용 블록이 나타나는 현상 발생

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone2#7]
엔트리에서 드론을 연결하였는데 아래 그림과 같이 센서 블록 중에 자동차(드라이브)용 옵션이 나타납니다. 드론용 옵션으로 변경 부탁드립니다.

<수정할 사항>
1. '자동차 동작 상태' 옵션 제거
2. '비행 동작 상태'와 '기본 좌표계' 옵션 추가

![image](https://user-images.githubusercontent.com/42791314/65398059-e88d3000-ddef-11e9-9dc4-a1c2e953fa50.png)

**Comment by realwolf** [comment]
https://github.com/entrylabs/entryjs/pull/1479
수정해서 PR 요청하였습니다.

**Comment by HhanGgun** [comment]
수고하셨습니다! 이번달에 엔트리에 적용되면 확인해보겠습니다. 감사합니다.

**Comment by realwolf** [comment]
https://github.com/entrylabs/entryjs/pull/1479
pr이 merge 되었습니다.
이달 말에 릴리즈되지 않을까 싶네요.

**Comment by HhanGgun** [comment]
넵, 릴리즈되면 확인해보겠습니다. 감사합니다!

**Comment by realwolf** [comment]
![image](https://user-images.githubusercontent.com/1720143/108127918-5164fe80-70ef-11eb-9838-6e9bf81aaa2c.png)
수정되었습니다.
이제 확인했네요.
