### ISSUE TITLE
[엔트리] 드론 연결 시 LED 관련 블록 중에서 한 블록의 초기값이 숫자로 표시됨

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone2#8]
드론 연결 시 LED 관련 블록 중에서 한 블록의 초기값이 아래 그림과 같이 숫자로 표시됩니다. 다른 블록과 마찬가지로 초기값을 '눈'으로 수정 부탁드립니다.
※ 옵션은 정상적으로 눈, 팔 2가지로 나옵니다.

![image](https://user-images.githubusercontent.com/42791314/65398608-440ced00-ddf3-11e9-85d2-978131a6787a.png)

**Comment by realwolf** [comment]
https://github.com/entrylabs/entryjs/pull/1479
수정해서 PR 요청하였습니다.

**Comment by HhanGgun** [comment]
수고하셨습니다! 이번달에 엔트리에 적용되면 확인해보겠습니다. 감사합니다.

**Comment by realwolf** [comment]
https://github.com/entrylabs/entryjs/pull/1479
pr이 merge 되었습니다.

**Comment by HhanGgun** [comment]
넵, 이번달에 릴리즈되면 확인해보겠습니다. 감사합니다!

**Comment by realwolf** [comment]
![image](https://user-images.githubusercontent.com/1720143/108128096-9b4de480-70ef-11eb-9b34-28e8c064f218.png)
수정 반영되었습니다.
