### ISSUE TITLE
[엔트리] 조종기 LED 관련 블록 중에서 한 블록의 초기값이 '200'으로 표시됨

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone2#9]
드론 또는 조종기 연결 시 조종기 LED 관련 블록 중에서 한 블록의 초기값이 아래 그림과 같이 '200'으로 표시됩니다. 다른 블록과 마찬가지로 초기값을 '255'로 수정 부탁드립니다.

![image](https://user-images.githubusercontent.com/42791314/65398784-2be99d80-ddf4-11e9-8c84-a10fbcf21846.png)

**Comment by realwolf** [comment]
사용 목적과 범위가 다른 값이라 255로 동일하게 만들면 혼란을 줄 것으로 예상되어 수정하지 않았습니다.

**Comment by HhanGgun** [comment]
넵 알겠습니다. 감사합니다.

**Comment by realwolf** [comment]
값들이 통일되지 않은 것을 뒤늦게 확인했습니다.
Interval의 초기값을 모두 500으로 변경했습니다.
